export const states = [
    { id: 'Tunis', name: 'Tunis' },
    { id: 'Ariana', name: 'Ariana' },
    { id: 'BenArous', name: 'Ben Arous' },
    { id: 'Manouba', name: 'Manouba' },
    { id: 'Nabeul', name: 'Nabeul' },
    { id: 'Bizerte', name: 'Bizerte' },
    { id: 'Beja', name: 'Beja' },
    { id: 'Jendouba', name: 'Jendouba' },
    { id: 'ElKef', name: 'El Kef' },
    { id: 'Siliana', name: 'Siliana' },
    { id: 'Kairouan', name: 'Kairouan' },
    { id: 'Kasserine', name: 'Kasserine' },
    { id: 'SidiBouzid', name: 'Sidi Bouzid' },
    { id: 'Sousse', name: 'Sousse' },
    { id: 'Monastir', name: 'Monastir' },
    { id: 'Mahdia', name: 'Mahdia' },
    { id: 'Sfax', name: 'Sfax' },
    { id: 'Gabes', name: 'Gabes' },
    { id: 'Medenine', name: 'Medenine' },
    { id: 'Tataouine', name: 'Tataouine' },
    { id: 'Gafsa', name: 'Gafsa' },
    { id: 'Tozeur', name: 'Tozeur' },
    { id: 'Kebili', name: 'Kebili' }
];

export const cities = {
    Tunis: ['La Marsa', 'Le Bardo', 'Carthage', 'El Menzah', 'Centre Ville', 'El Omrane', 'Sidi Hassine', 'Bab Souika', 'Lafayette'],
    Ariana: ['Ariana', 'La Soukra', 'Raoued', 'Kalaat El Andalous', 'Borj El Baccouche', 'Mnihla', 'Cité Ghazela'],
    BenArous: ['Ben Arous', 'Hammam Lif', 'Rades', 'Mornag', 'Bou Mhel', 'Hammam Chott', 'Mohamedia'],
    Manouba: ['Manouba', 'Djedeida', 'Oued Ellil', 'Tebourba', 'Borj El Amri', 'Mornaguia'],
    Nabeul: ['Nabeul', 'Hammamet', 'Kelibia', 'Korba', 'Menzel Temime', 'Takelsa', 'Soliman', 'Grombalia'],
    Bizerte: ['Bizerte', 'Menzel Bourguiba', 'Ras Jebel', 'Mateur', 'Sejnane', 'Tinja', 'Ghar El Melh'],
    Beja: ['Beja', 'Medjez El Bab', 'Testour', 'Nefza', 'Teboursouk', 'Goubellat'],
    Jendouba: ['Jendouba', 'Tabarka', 'Bou Salem', 'Ain Draham', 'Fernana', 'Beni Mtir'],
    ElKef: ['Le Kef', 'Dahmani', 'Tajerouine', 'Sakiet Sidi Youssef', 'Nebeur', 'Jerissa', 'Kalaat Senan'],
    Siliana: ['Siliana', 'Makthar', 'Bargou', 'Bou Arada', 'Gaafour', 'Kesra', 'Rouhia'],
    Kairouan: ['Kairouan', 'Chebika', 'Haffouz', 'Nasrallah', 'Oueslatia', 'Sbikha', 'Hajeb El Ayoun'],
    Kasserine: ['Kasserine', 'Sbeitla', 'Foussana', 'Thala', 'Feriana', 'Hidra', 'Majel Bel Abbès'],
    SidiBouzid: ['Sidi Bouzid', 'Regueb', 'Meknassy', 'Jilma', 'Sidi Ali Ben Aoun', 'Menzel Bouzaiane', 'Ouled Haffouz'],
    Sousse: ['Sousse', 'Hammam Sousse', 'Msaken', 'Kalâa Kebira', 'Kalâa Seghira', 'Akouda', 'Enfidha'],
    Monastir: ['Monastir', 'Sahline', 'Ksibet El Mediouni', 'Jemmal', 'Beni Hassen', 'Bekalta', 'Teboulba'],
    Mahdia: ['Mahdia', 'Chebba', 'El Jem', 'Melloulèche', 'Rejiche', 'Ksour Essef', 'Bou Merdes'],
    Sfax: ['Sfax', 'Agareb', 'Kerkennah', 'El Hencha', 'Bir Ali Ben Khalifa', 'Mahrès', 'Skhira'],
    Gabes: ['Gabes', 'Mareth', 'Matmata', 'Chenini Nahal', 'Ghannouch', 'Hamma', 'Menzel Habib'],
    Medenine: ['Medenine', 'Zarzis', 'Djerba Midoun', 'Djerba Houmt Souk', 'Djerba Ajim', 'Ben Guerdane', 'Boughrara'],
    Tataouine: ['Tataouine', 'Ghomrassen', 'Bir Lahmar', 'Dehiba', 'Remada'],
    Gafsa: ['Gafsa', 'Metlaoui', 'Redeyef', 'El Guettar', 'Mdhila', 'Oum Laarayes', 'Belkhir'],
    Tozeur: ['Tozeur', 'Nefta', 'Degache', 'Hazoua', 'Tamaghza'],
    Kebili: ['Kebili', 'Douz', 'Souk Lahad', 'El Faouar', 'Bechni']
};
